{
 "title": "MM2",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "MM2-Repl-Latency-Ms-Avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (topic) (connect_mirror_mirrorsourceconnector_replication_latency_ms)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MM2-Consumer-Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lag_avg",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MM2-Record-Age-Ms-Avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connect_mirror_mirrorsourceconnector_record_age_ms",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MM2-Consumer-Fetch-Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_latency_avg{app=\"connect\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MM2-Source-Task",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_source_task_source_record_active_count{connector!=\"mm2-hbc\"}"
    },
    {
     "expr": "kafka_consumer_incoming_byte_total{clientId=~\"consumer-mm2-msc-cons-[0-9]+\"}/1000000"
    }
   ]
  }
 ]
}